module.exports = function(grunt) {
    require('load-grunt-tasks')(grunt);
    grunt.loadNpmTasks('grunt-contrib-clean');
    grunt.loadNpmTasks('grunt-mocha-test');
    grunt.loadNpmTasks('grunt-mocha-istanbul');
    grunt.loadNpmTasks('grunt-aws-lambda');
    grunt.loadNpmTasks('grunt-es6-transpiler');

    grunt.initConfig(
        {
            // Get rid of stuff generated by builds
            clean:
            {
                options:
                {
                    force: true,
                },
                dist: ['dist/*'],
                coverage: ['coverage/*'],
                ciCoverage: 'xunit.xml',
            },

            eslint:
            {
                options: {},
                target: ['.'],  // Use directories instead of wildcards (like *.js) or you will get a warning for every ignored file!
            },

            mocha_istanbul:
            {
                // For mortals
                coverage:
                {
                    src: 'test', // the folder, not the files
                    options:
                    {
                        reportFormats: ['html'],
                        coverageFolder: 'coverage',
                        mask: '**/*.js',
                        quiet: false,
                        clearRequireCache: true,           // Optionally clear the require cache before running tests (defaults to false)
                        reporter: 'spec',
                    },
                },

                // For automated CI envs. This will run the tests and coverage at the same time
                // and will output the test results in J/XUnit xml format and the coverage in cobertura
                ciCoverage:
                {
                    src: 'test', // the folder, not the files
                    options:
                    {
                        reportFormats: ['cobertura', 'html'],
                        coverageFolder: 'coverage',
                        mask: '**/*.js',
                        quiet: true,
                        clearRequireCache: true,           // Optionally clear the require cache before running tests (defaults to false)
                        reporter: 'xunit-file',
                    },
                },
            },

            es6transpiler:
            {
                'default':
                {
                    files:
                    {
                        'wundergroundMonitor_es5.js' : 'wundergroundMonitor.js',
                    },
                },
            },

            lambda_package:
            {
                'default':
                {
                    options:
                    {
                        include_files: ['*.js', '*.json', 'lib/**/*.js', 'node_modules/**/*.js', 'node_modules/**/*.json'],
                    },
                },
            },

            lambda_deploy:
            {
                'default':
                {
                    arn: 'arn:aws:lambda:us-west-2:281650663203:function:sendMinimumForecast',
                    options:
                    {
                        region: 'us-west-2',
                    },
                },
            },

            lambda_invoke:
            {
                'default':
                {
                    options:
                    {
                        file_name: 'wundergroundMonitor_es5.js',
                        handler: 'sendMinimumForecast',
                        event: 'test/data/lambda_event.json',
                    },
                },
            },
        });

    grunt.registerTask('coverage', ['mocha_istanbul:coverage']);
    grunt.registerTask('lint', ['eslint']);
    grunt.registerTask('test', ['coverage']);
    grunt.registerTask('deploy', ['clean', 'es6transpiler', 'lambda_package', 'lambda_deploy']);
    grunt.registerTask('invoke', ['es6transpiler', 'lambda_invoke']);

    grunt.registerTask('default', ['lint', 'test']);
};
