module.exports = function(grunt) {
    require('load-grunt-tasks')(grunt);
    grunt.loadNpmTasks('grunt-mocha-test');
    grunt.loadNpmTasks('grunt-mocha-istanbul');
    grunt.loadNpmTasks('grunt-contrib-clean');

    grunt.initConfig(
        {
            // Get rid of stuff generated by builds
            clean: ['coverage/', 'xunit.xml'],

            eslint: {
                options: {},
                target: ['.'],  // Use directories instead of wildcards (like *.js) or you will get a warning for every ignored file!
            },

            mocha_istanbul: {
                // For mortals
                coverage: {
                    src: 'test', // the folder, not the files
                    options: {
                        reportFormats: ['html'],
                        coverageFolder: 'coverage',
                        mask: '**/*.js',
                        quiet: false,
                        clearRequireCache: true,           // Optionally clear the require cache before running tests (defaults to false)
                        reporter: 'spec',
                    },
                },

                // For automated CI envs. This will run the tests and coverage at the same time
                // and will output the test results in J/XUnit xml format and the coverage in cobertura
                ciCoverage: {
                    src: 'test', // the folder, not the files
                    options: {
                        reportFormats: ['cobertura', 'html'],
                        coverageFolder: 'coverage',
                        mask: '**/*.js',
                        quiet: true,
                        clearRequireCache: true,           // Optionally clear the require cache before running tests (defaults to false)
                        reporter: 'xunit-file',
                    },
                },
            },
        });

    grunt.registerTask('coverage', ['mocha_istanbul:coverage']);
    grunt.registerTask('lint', ['eslint']);
    grunt.registerTask('test', ['lint', 'coverage']);

    grunt.registerTask('default', ['test']);
};
